# save_dir: /data/xueyi/softzoo_diffusion
# save_dir: /data/xueyi/uni_manip/exp
save_dir: /data/xueyi/uni_manip/tds_diffusion_exp

# eval_during_traini
seed: 42

# exp_tag: test_scalev2_saved_ #  test_scalev2_
# exp_tag: test_scalev2_saved_mlpnet_ #  test_scalev2_
# exp_tag: test_scalev3_
# exp_tag: test_scaled_pcd_
# exp_tag: test_1_
# exp_tag: test_v2_
# exp_tag: test_v2_loadfromsv_
# exp_tag: test_v2_new_
# exp_tag: test_v2_new_loadfromsv_
# exp_tag: test_v3_loadfromsv_
# exp_tag: test_v3_test_transformer_
# exp_tag: test_v3_scale_v2_
# exp_tag: test_v3_scale_v2_testx_
# exp_tag: test_v3_scale_v2_testx_model_v2_
# exp_tag: test_v3_scale_v2_testx_model_v3_
# exp_tag: test_v3_scale_v2_testx_model_nscale_
# exp_tag: test_v3_scale_v2_testx_model_nscale_tsemb_v2_
# exp_tag: test_scale_ori_transformer_v2_
# exp_tag: test_scale_ori_transformer_v3_
# exp_tag: test_scale_ori_transformer_v4_
# exp_tag: test_scale_ori_transformer_v5_
exp_tag: test_scale_ori_transformer_v6_ori_

model:
  n_layers: 7
  n_layers_act: 7
  input_dims:
    X: 2
    E: 1
    y: 1
  hidden_mlp_dims: 
    X: 128
    E: 128
    y: 128
  hidden_dims:
    dx: 256
    de: 256
    dy: 256
    n_head: 4
    dim_ffX: 256
    dim_ffE: 256
  output_dims:
    X: 2
    E: 1
    y: 1
  
  ### for the act model ###
  input_dims_act:
    X: 630
    y: 1
  hidden_mlp_dims_act:
    X: 4096
    y: 1024
  output_dims_act:
    X: 630

  ### for pcd with acts ###
  n_layers_pc: 7
  input_dims_pc:
    pos: 2
    X: 2
    feat: 20
  hidden_mlp_dims_pc: 
    X: 1024
    feat: 1024
    t: 256
  output_dims_pc:
    X: 2
    feat: 20

  ### for pcd with segs ###
  n_layers_segs: 7
  input_dims_segs:
    pos: 2 
    segs: 21
  hidden_mlp_dims_segs: 
    X: 1024
    segs: 1024
    t: 256
  output_dims_segs:
    X: 2
    segs: 21

  ### for 3d cd with acts ###
  n_layers_3d_pc: 7
  input_dims_3d_pc:
    pos: 3
    X: 3
    feat: 900
  hidden_mlp_dims_3d_pc: 
    X: 1024
    feat: 2048
    t: 256
  output_dims_3d_pc:
    X: 3
    feat: 900

  ### for 3d cd with acts ###
  n_layers_3d_pc_v2: 7
  input_dims_3d_pc_v2:
    pos: 3
    X: 3
    feat: 900
  hidden_mlp_dims_3d_pc_v2: 
    X: 1024
    feat: 2048
    t: 256
  output_dims_3d_pc_v2:
    X: 3
    feat: 900
  

diffusion:
  noise_schedule: linear
  sigma_small: True
  lambda_vel: 0.0
  lambda_rcxyz: 0.0
  lambda_fc: 0.0
  # denoising_stra: 
  # inter_optim: 

dataset:
  dataset_type: uni_manip
  num_frames: 10
  # data_folder: /data/xueyi/softzoo/data/uni_manip_2d_data
  # data_folder: /data2/xueyi/uni_manip/data
  # data_folder: /data/xueyi/softzoo/expv4
  # data_folder: /data/xueyi/softzoo
  data_folder: /data/xueyi/softzoo

dataset_act:
  # data_folder: /data2/xueyi/uni_manip/data
  # data_folder: /data/xueyi/softzoo/exp
  # data_folder: /data2/xueyi/uni_manip/exp_v2/exp
  # data_folder: /data/xueyi/softzoo/expv4
  data_folder: /data/xueyi/softzoo

dataset_3d_pc:
  single_inst: True
  # single_inst: False
  data_folder: /data/xueyi/uni_manip



task:
  dt: 1e-1
  nn_timesteps: 10
  use_target_data: True
  sample_wconstraints: True


training:

  batch_size: 32
  lr: 1e-4
  log_interval: 10
  save_interval: 200
  resume_checkpoint: False
  weight_decay: 5e-5
  lr_anneal_steps: 5000000
  num_steps: 5000000
  w_glb_traj_feat_cond: False
  # resume pahs
  # resume_checkpoint_graph: /data2/xueyi/uni_manip/exp/test_scalev2_saved_mlpnet_/model000383000.pt
  # resumd_checkooit_act: /data2/xueyi/uni_manip/exp/test_scalev3_/model000200000.pt
  # resume_checkpoint_pc: "/data/xueyi/uni_manip/tds_diffusion_exp/test_v2_/model000065000.pt"
  resume_checkpoint_pc: ""
  # resume_checkpoint_pc: "/data/xueyi/uni_manip/tds_diffusion_exp/test_v2_new_/model000001000.pt"

eval_during_training: False  
