defaults:
  - _self_
  # - agent: ddpg # sac
# 
seed: 42 #  0 #  42
# seed: 3407
# seed: 0 #  0 #  42


sampled_graph_wacts_sv_rt_dict: /data2/xueyi/uni_manip/exp/eval_combined_v1_/eval_combined_v1_/sampled_projected_rt_dict.npy

uni_manip:
  fixed_y_len: 0.05
  base_x_len: 0.1
  st_len_one_side: 0.2
  ed_len_one_side: 0.4
  nn_stages: 6

## contact spring d: 1e-1 ## #
## 

sim:
  # contact_spring_d: 1e-1 # 5e-1 #
  contact_spring_d:  5e-1
  contact_damping_d: 1e-1

optimization:
  inherit_from_prev: False
  # inherit_from_prev: True
  link_rotational_lr: 0.001
  link_translational_lr: 0.001



general:
  vis: False
  save_ckpts: False
  use_wandb: False


task:
  goal_x: 0.7
  goal_y: 0.3
  nn_timesteps: 10
  dt: 1e-1
  dim: 2

run:
  root_dir: /data2/xueyi/softzoo # /data/xueyi/softzoo
  proj_dir: /home/xueyi/diffsim/softzoo
  start_inst_idx: 2 # 0
  # start_inst_idx: 1

# seeds: 
# - 3407
# - 42
# - 0
#  # https://arxiv.org/abs/2109.08203

# tag: null
# env_name: LunarLanderContinuous-v2
# vec_envs: 1

# train:
#   nstep: ${buffer.nstep}
#   vec_envs: ${vec_envs}
#   timesteps: 200_000
#   batch_size: 128
#   plot_interval: 5000
#   eval_interval: 5000
#   eval_episodes: 5

# buffer:
#   capacity: 200_000
#   use_per: False
#   nstep: 1
#   gamma: ${agent.gamma}
#   per_alpha: 0.7
#   per_beta: 0.4
#   per_eps: 0.01


hydra:
  job:
    chdir: true
  run:
    dir: /data/xueyi/softzoo/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${hydra.job.override_dirname}
