
# Task name - used to pick the class to load
task_name:  ${task.name}
# experiment name. defaults to name of training config
experiment: ''

# if set to positive integer, overrides the default number of environments
num_envs: ''

# seed - set to -1 to choose random seed
seed: 42
# set to True for deterministic performance
torch_deterministic: False

# set the maximum number of learning iterations to train for. overrides default per-environment setting
max_iterations: ''

enableCameraSensors: False

## Device config
#  'physx' or 'flex'
physics_engine: 'physx'
# whether to use cpu or gpu pipeline
pipeline: 'gpu'
# device for running physics simulation
sim_device: 'cuda:2'
# device to run RL
rl_device: 'cuda:2'

# pipeline: 'cpu'
# # device for running physics simulation
# sim_device: 'cpu'
# # device to run RL
# rl_device: 'cpu'
graphics_device_id: 0

## PhysX arguments
num_threads: 4 # Number of worker threads per scene used by PhysX - for CPU PhysX only.
solver_type: 1 # 0: pgs, 1: tgs
num_subscenes: 4 # Splits the simulation into N physics scenes and runs each one in a separate thread

# RLGames Arguments
# test - if set, run policy in inference mode (requires setting checkpoint to load)
test: False
# used to set checkpoint path
checkpoint: ''
# set sigma when restoring network
sigma: ''
# set to True to use multi-gpu training
multi_gpu: False

wandb_activate: False
wandb_group: ''
wandb_name: ${train.params.config.name}
wandb_entity: ''
wandb_project: 'isaacgymenvs'
wandb_tags: []
wandb_logcode_dir: '' 

# capture_video: False
capture_video: True
capture_video_freq: 1464
# capture_video_len: 135
capture_video_len: 300
force_render: True

render_mode: 'ansi'

exp_dir: '/cephfs/xueyi/exp/IsaacGymEnvs/isaacgymenvs'
tag: 'exp'

# disables rendering
headless: False

# set default task and default training config based on task
defaults:
  - task: Ant
  - train: ${task}PPO
  - hydra/job_logging: disabled
  - pbt: no_pbt

# sv_gt_refereces_fn: /home/xueyi/diffsim/Control-VAE/ReferenceData/shadow_taco_train_split_20231105_067_spoon2_data_opt_tag_optrulesrobo.npy

# set the directory where the output files get saved
hydra:
  output_subdir: null
  run:
    dir: .


### many and mnay and a lot of things should be optimized here ###

# ###### 20231105_067 -- spoon2 (test) #########
# scaled_object_asset_file: 'taco_20231105_067_wocollision'
# gt_data_fn: '/home/xueyi/diffsim/Control-VAE/ReferenceData/shadow_taco_train_split_20231105_067_spoon2_data_opt_tag_optrulesrobo.npy'
# ###### 20231105_067 -- spoon2 (test) #########


# scaled_object_asset_file: 'taco_20230927_037_wcollision.urdf'
# gt_data_fn: '/home/xueyi/diffsim/Control-VAE/ReferenceData/shadow_taco_train_split_20230927_037_brush3_data_opt_tag_optrobo1.npy'

# ######## 20230930_001 ########
# scaled_object_asset_file: 'taco_20230930_001_wcollision.urdf'
# gt_data_fn: '/home/xueyi/diffsim/Control-VAE/ReferenceData/shadow_taco_train_split_20230930_001_plank1_data.npy'


######## 20231031_184 ########
# scaled_object_asset_file: 'taco_20231031_184_wcollision.urdf'
# gt_data_fn: '/home/xueyi/diffsim/Control-VAE/ReferenceData/shadow_taco_train_split_20231031_184_hammer20231031_184_data.npy'

# ######## 20231031_171 ########
# scaled_object_asset_file: 'taco_20231031_171_wcollision.urdf'
# gt_data_fn: '/home/xueyi/diffsim/Control-VAE/ReferenceData/shadow_taco_train_split_20231031_171_hammer20231031_171_data.npy'



# ######## 20231027_067 ########
# scaled_object_asset_file: 'taco_20231027_067_wcollision.urdf'
# gt_data_fn: '/home/xueyi/diffsim/Control-VAE/ReferenceData/shadow_taco_train_split_20231027_067_shovel20231027_067_data.npy'

# ######## 20231027_067 ########
# scaled_object_asset_file: 'taco_20231027_066_wcollision.urdf'
# gt_data_fn: '/home/xueyi/diffsim/Control-VAE/ReferenceData/shadow_taco_train_split_20231027_066_shovel20231027_066_data.npy'



# ######## 20231027_067 ########
# scaled_object_asset_file: 'taco_20231027_068_wcollision.urdf'
# gt_data_fn: '/home/xueyi/diffsim/Control-VAE/ReferenceData/shadow_taco_train_split_20231027_068_shovel20231027_068_data.npy'


# ######## 20231027_067 ########
# scaled_object_asset_file: 'taco_20231027_087_wcollision.urdf'
# gt_data_fn: '/home/xueyi/diffsim/Control-VAE/ReferenceData/shadow_taco_train_split_20231027_087_shovel20231027_087_data.npy'


# ######## 20231027_022 ########
# scaled_object_asset_file: 'taco_20231027_022_wcollision.urdf'
# gt_data_fn: '/home/xueyi/diffsim/Control-VAE/ReferenceData/shadow_taco_train_split_20231027_022_shovel20231027_022_data.npy'


# ######## 20231027_022 ########
# scaled_object_asset_file: 'taco_20231027_027_wcollision.urdf'
# gt_data_fn: '/home/xueyi/diffsim/Control-VAE/ReferenceData/shadow_taco_train_split_20231027_027_20231027_027_data.npy'


# ######## 20231027_022 ########
# scaled_object_asset_file: 'taco_20231027_066_wcollision.urdf'
# gt_data_fn: '/home/xueyi/diffsim/Control-VAE/ReferenceData/shadow_taco_train_split_20231027_066_20231027_066_data.npy'


# ######## 20231027_022 ########
# scaled_object_asset_file: 'taco_20231027_114_wcollision.urdf'
# gt_data_fn: '/home/xueyi/diffsim/Control-VAE/ReferenceData/shadow_taco_train_split_20231027_114_20231027_114_data.npy'


######## 20231027_022 ########
# scaled_object_asset_file: 'taco_20231027_130_wcollision.urdf'
# gt_data_fn: '/home/xueyi/diffsim/Control-VAE/ReferenceData/shadow_taco_train_split_20231027_130_20231027_130_data.npy'

# ######## grab - mouse ########
# scaled_object_asset_file: 'grab_mouse_wcollision.urdf'
# gt_data_fn: '/home/xueyi/diffsim/Control-VAE/ReferenceData/shadow_grab_train_split_102_mouse_data_opt.npy'


# ######## grab - mouse ########
# scaled_object_asset_file: 'grab_bunny_wcollision.urdf'
# gt_data_fn: '/home/xueyi/diffsim/Control-VAE/ReferenceData/shadow_grab_train_split_85_bunny_data_opt.npy'


######## grab - mouse ########
# scaled_object_asset_file: 'taco_20231026_002_wcollision.urdf'
# gt_data_fn: '/home/xueyi/diffsim/Control-VAE/ReferenceData/shadow_taco_train_split_20231026_002_20231026_002_data.npy'


# scaled_object_asset_file: 'grab_stapler107_wcollision.urdf'
# gt_data_fn: '/home/xueyi/diffsim/Control-VAE/Data/ReferenceData/shadow_grab_train_split_107_stapler107_data_fingerretar.npy'


# two_hands: True
# scaled_object_asset_file: 'arctic_mixer_wcollision.urdf'
# gt_data_fn: '/home/xueyi/diffsim/Control-VAE/ReferenceData/shadow_arctic_s05_mixer_data_v3.npy'


# two_hands: False
# scaled_object_asset_file: 'grab_mouse_wcollision.urdf'
# gt_data_fn: '/home/xueyi/diffsim/Control-VAE/ReferenceData/shadow_grab_mouse_102_dgrasptracking.npy'




# two_hands: False
# scaled_object_asset_file: 'grab_bunny_wcollision.urdf'
# gt_data_fn: '/home/xueyi/diffsim/Control-VAE/ReferenceData/shadow_grab_bunny_85_dgrasptracking.npy'


# two_hands: False
# scaled_object_asset_file: 'taco_20231105_067_wocollision.urdf'
# gt_data_fn: '/home/xueyi/diffsim/Control-VAE/ReferenceData/shadow_taco_spoon2_idx_20231105_067_dgrasptracking.npy'


# two_hands: True
# scaled_object_asset_file: 'arctic_mixer_wcollision.urdf'
# gt_data_fn: '/home/xueyi/diffsim/Control-VAE/ReferenceData/shadow_arctic_s05_mixer_data_v3_opt2.npy'



# two_hands: True
# scaled_object_asset_file: 'arctic_phone_wcollision.urdf'
# gt_data_fn: '/home/xueyi/diffsim/Control-VAE/ReferenceData/shadow_arctic_s07_phone_data_v3_opt2.npy'



# two_hands: True
# scaled_object_asset_file: 'arctic_ketchup_wcollision.urdf'
# gt_data_fn: '/home/xueyi/diffsim/Control-VAE/ReferenceData/shadow_arctic_s07_ketchup_data_v3_opt2.npy'

two_hands: True
scaled_object_asset_file: 'arctic_microwave_wcollision.urdf'
gt_data_fn: '/home/xueyi/diffsim/Control-VAE/ReferenceData/shadow_arctic_s06_microwave_data_v3_opt2.npy'